services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: omni-feed-hub-dev
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./coverage:/usr/src/app/coverage
    environment:
      - NODE_ENV=development
    command: pnpm start:dev
    # Ajout pour les tests
    extra_hosts:
      - "localhost:host-gateway"
